### ISSUE TITLE
Add a hook to allow users to push on build

### ISSUE THREAD

**Issue by mike-solomon** [moderneinc/enterprise-jenkins-ingest#8]
Right now, if users select to use this ingest, they have to specify a time for the ingestion. While there are some upsides to that, one possible negative is that artifacts could be delayed by up to 24 hours. It was suggested [here](https://github.com/moderneinc/enterprise-jenkins-ingest/pull/7#discussion_r995991237) that a hook could be added to allow users to forego that time in favor of just doing it on every build.

**Comment by okundzich** [comment]
The purpose of this ingest right now is a nightly batch ingest produced by the central team without modifying existing repositories. If they want to publish on every commit/CI build, the team themselves can add moderne build plugins and publish on every CI build. So I don't think this will ever become a priority for us.
